---
- name: Copy zoo.cfg
  template: src=zoo.cfg dest={{install_dir}}/apache-zookeeper-{{zookeeper_version}}-bin/conf mode=644 owner={{ user }} group = {{ group }}

- name: Copy log4j
  template: src=log4j.properties dest={{install_dir}}/apache-zookeeper-{{zookeeper_version}}-bin/conf mode=644 owner={{ user }} group = {{ group }}

- name: Copy zkEnv Shell
  template: src=zkEnv.sh dest={{install_dir}}/apache-zookeeper-{{zookeeper_version}}-bin/bin mode=755 owner={{ user }} group = {{ group }}

- name: Copy zkServer Shell
  template: src=zkServer.sh dest={{install_dir}}/apache-zookeeper-{{zookeeper_version}}-bin/bin mode=755 owner={{ user }} group = {{ group }}

- name: Copy setId Shell
  template: src=setId.sh dest={{install_dir}}/apache-zookeeper-{{zookeeper_version}}-bin/bin mode=755 owner={{ user }} group = {{ group }}

- name: set Id
  shell: 'source {{install_dir}}/apache-zookeeper-{{zookeeper_version}}-bin/bin/setId.sh'
  become: yes
  become_user: "{{ user }}"

- name: Copy Zookeeper Env Script
  template: src=zookeeper_env.sh dest=/etc/profile.d/ mode=755

- name: Set Zookeeper Env
  shell: source /etc/profile.d/zookeeper_env.sh
  become: yes
  become_user: "{{ user }}"