---
- name: Create Data Dir
  file:  path={{item}} state=directory owner={{ user }} group={{ group}} mode="u=rwx,g=r,o=r"
  with_items:
    - "{{ data_dir }}"
    - "{{ zookeeper_log_path }}"

- name: Copy Package
  copy: src={{ download_path }}/apache-zookeeper-{{zookeeper_version}}-bin.tar.gz dest={{ tmp_path }} owner={{ user }} mode=755

- name: Extract zookeeper archive
  command: chdir={{install_dir}}/ /bin/tar xvf {{ tmp_path }}/apache-zookeeper-{{zookeeper_version}}-bin.tar.gz -C {{install_dir}}/

- name: Change Owner
  shell: "chown {{ user }}:{{ group }} {{install_dir}}/apache-zookeeper-{{zookeeper_version}}-bin -R" 