- hosts: master 
  remote_user: root
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_master.yml
   - vars/var_hive.yml
  vars:
     open_firewall: false
     install_hive: true
     config_hive: true
     init_hive: true
  roles:
    - hive
