- hosts: spark 
  remote_user: root
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_master.yml
   - vars/var_spark.yml
  vars:
     open_firewall: false       # firewalld
     install_spark: true        # install spark
     config_spark:  true        # config spark
     install_scala: true        # install scala
  roles:
    - spark
