---

- name: Unzip Hbase
  unarchive: src={{ download_path }}/hbase-{{hbase_version}}-bin.tar.gz dest={{ hbase_path }} owner={{ user }} group={{ group }} mode=755 

- name: Change Owner
  shell: "chown {{ user }}:{{ group }} {{ hbase_path }}/hbase-{{hbase_version}} -R"